# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
